config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

  resources :users, only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

    before_save { self.email = email.downcase }
    after_create :send_user_emails


    private
    
    def send_user_emails
        UserMailer.new_user(self).deliver_now
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:username, :email)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", welcome_index_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
        <% if user_signed_in? %>
          <div class="pull-right user-info">
            <li class="pull-left"><%= link_to current_user.name, user_path(current_user) %></li> <br>
            <li class="pull-left"><%= link_to "Sign Out", session_path(current_user), method: :delete %></li>
          </div> 
          <div class="pull-right avatar">
            <li class="pull-right"><%= image_tag current_user.avatar_url(48) %></li> 
          </div>
                      
        <% else %>
          <li class="pull-right"><%= link_to "Sign In", new_user_session_path %></li>
          <li class="pull-right"><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
      
    
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h2>Sign up</h2>

<div class="row">
   <div class="col-md-8">
       <%= form_for @user do |f| %>
           <% if @user.errors.any? %>
               <div class="alert alert-danger">
                   <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
                   <ul>
                       <% @user.errors.full_messages.each do |msg| %>
                           <li><%= msg %></li>
                       <% end %>
                   </ul>
               </div>
           <% end %>
           <%= form_group_tag(@user.errors[:name]) do %>
               <%= f.label :name %>
               <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
           <% end %>
           <%= form_group_tag(@user.errors[:email]) do %>
               <%= f.label :email %>
               <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
           <% end %>
           <%= form_group_tag(@user.errors[:password]) do %>
               <%= f.label :password %>
               <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
           <% end %>
           <%= form_group_tag(@user.errors[:password_confirmation]) do %>
               <%= f.label :password_confirmation %>
               <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
           <% end %>
           <div class="form-group">
               <%= f.submit "Sign up", class: 'btn btn-success' %>
           </div>
     <% end %>
 </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
<h1>Blocipedia</h1>
<p>Bloccipedia is a resource for creating public and private Markdown-based wikis</p>
<p>
    
</p>
</div>


</div>